# Generated by Django 5.0.3 on 2024-08-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='permiso',
        ),
        migrations.AddField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='Sticker_totoro', max_length=40),
            preserve_default=False,
        ),
    ]
