# Generated by Django 5.0.3 on 2024-09-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prod', models.CharField(max_length=8)),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField(default=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
