# Generated by Django 5.0.3 on 2024-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0006_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
