# Generated by Django 5.0.3 on 2024-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0007_imagenprod_remove_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProd',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
