# Generated by Django 5.0.3 on 2024-09-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0008_delete_imagenprod_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
