# Generated by Django 5.0.3 on 2024-09-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppImportaciones', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
