# Generated by Django 5.0.3 on 2024-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_imagen_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
